name: push MadGraph-ROOT-Delphes

on:
  push:
    branches: [ main ]
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Check out code

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: melashri/hep-tools
        registry: docker.io
        directory: MadGraph-Delphes-ROOT
        dockerfile: MadGraph-Delphes-ROOT/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

